services:
  - type: web
    name: listsync-server
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: VERIFICATION_TOKEN
        value: listsync_verification_token_change_me
      - key: ENDPOINT_URL
        sync: false
